spring.application.name=registro

# Datasource (contenedor Docker named 'educaflow-db' -> host 'localhost' assuming port forwarding 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/educaflow
spring.datasource.username=educaflow
spring.datasource.password=educaflow
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Thymeleaf
spring.thymeleaf.cache=false

# Server port
server.port=8081

# Código del centro activo en Axelor al que se asignarán los usuarios registrados
app.centro.code=MISLATA

